# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2015, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.9 on 2016-07-04 17:56:45.

require 'ads_common/savon_service'
require 'bing_ads_api/v10/campaign_management_service_registry'

module BingAdsApi; module V10; module CampaignManagementService
  class CampaignManagementService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://bingads.microsoft.com/CampaignManagement/v10'
      super(config, endpoint, namespace, :v10)
    end

    def add_campaigns(*args, &block)
      return execute_action('add_campaigns', args, &block)
    end

    def get_campaigns_by_account_id(*args, &block)
      return execute_action('get_campaigns_by_account_id', args, &block)
    end

    def get_campaigns_by_ids(*args, &block)
      return execute_action('get_campaigns_by_ids', args, &block)
    end

    def delete_campaigns(*args, &block)
      return execute_action('delete_campaigns', args, &block)
    end

    def update_campaigns(*args, &block)
      return execute_action('update_campaigns', args, &block)
    end

    def get_negative_sites_by_campaign_ids(*args, &block)
      return execute_action('get_negative_sites_by_campaign_ids', args, &block)
    end

    def set_negative_sites_to_campaigns(*args, &block)
      return execute_action('set_negative_sites_to_campaigns', args, &block)
    end

    def get_config_value(*args, &block)
      return execute_action('get_config_value', args, &block)
    end

    def get_bsc_countries(*args, &block)
      return execute_action('get_bsc_countries', args, &block)
    end

    def add_ad_groups(*args, &block)
      return execute_action('add_ad_groups', args, &block)
    end

    def delete_ad_groups(*args, &block)
      return execute_action('delete_ad_groups', args, &block)
    end

    def get_ad_groups_by_ids(*args, &block)
      return execute_action('get_ad_groups_by_ids', args, &block)
    end

    def get_ad_groups_by_campaign_id(*args, &block)
      return execute_action('get_ad_groups_by_campaign_id', args, &block)
    end

    def update_ad_groups(*args, &block)
      return execute_action('update_ad_groups', args, &block)
    end

    def get_negative_sites_by_ad_group_ids(*args, &block)
      return execute_action('get_negative_sites_by_ad_group_ids', args, &block)
    end

    def set_negative_sites_to_ad_groups(*args, &block)
      return execute_action('set_negative_sites_to_ad_groups', args, &block)
    end

    def delete_targets_from_library(*args, &block)
      return execute_action('delete_targets_from_library', args, &block)
    end

    def get_targets_info_from_library(*args, &block)
      return execute_action('get_targets_info_from_library', args, &block)
    end

    def set_target_to_ad_group(*args, &block)
      return execute_action('set_target_to_ad_group', args, &block)
    end

    def delete_target_from_ad_group(*args, &block)
      return execute_action('delete_target_from_ad_group', args, &block)
    end

    def set_target_to_campaign(*args, &block)
      return execute_action('set_target_to_campaign', args, &block)
    end

    def delete_target_from_campaign(*args, &block)
      return execute_action('delete_target_from_campaign', args, &block)
    end

    def add_targets_to_library(*args, &block)
      return execute_action('add_targets_to_library', args, &block)
    end

    def update_targets_in_library(*args, &block)
      return execute_action('update_targets_in_library', args, &block)
    end

    def get_targets_by_ids(*args, &block)
      return execute_action('get_targets_by_ids', args, &block)
    end

    def get_targets_by_ad_group_ids(*args, &block)
      return execute_action('get_targets_by_ad_group_ids', args, &block)
    end

    def get_targets_by_campaign_ids(*args, &block)
      return execute_action('get_targets_by_campaign_ids', args, &block)
    end

    def add_ads(*args, &block)
      return execute_action('add_ads', args, &block)
    end

    def delete_ads(*args, &block)
      return execute_action('delete_ads', args, &block)
    end

    def get_ads_by_editorial_status(*args, &block)
      return execute_action('get_ads_by_editorial_status', args, &block)
    end

    def get_ads_by_ids(*args, &block)
      return execute_action('get_ads_by_ids', args, &block)
    end

    def get_ads_by_ad_group_id(*args, &block)
      return execute_action('get_ads_by_ad_group_id', args, &block)
    end

    def update_ads(*args, &block)
      return execute_action('update_ads', args, &block)
    end

    def add_keywords(*args, &block)
      return execute_action('add_keywords', args, &block)
    end

    def delete_keywords(*args, &block)
      return execute_action('delete_keywords', args, &block)
    end

    def get_keywords_by_editorial_status(*args, &block)
      return execute_action('get_keywords_by_editorial_status', args, &block)
    end

    def get_keywords_by_ids(*args, &block)
      return execute_action('get_keywords_by_ids', args, &block)
    end

    def get_keywords_by_ad_group_id(*args, &block)
      return execute_action('get_keywords_by_ad_group_id', args, &block)
    end

    def update_keywords(*args, &block)
      return execute_action('update_keywords', args, &block)
    end

    def appeal_editorial_rejections(*args, &block)
      return execute_action('appeal_editorial_rejections', args, &block)
    end

    def add_site_placements(*args, &block)
      return execute_action('add_site_placements', args, &block)
    end

    def delete_site_placements(*args, &block)
      return execute_action('delete_site_placements', args, &block)
    end

    def get_site_placements_by_ids(*args, &block)
      return execute_action('get_site_placements_by_ids', args, &block)
    end

    def get_site_placements_by_ad_group_id(*args, &block)
      return execute_action('get_site_placements_by_ad_group_id', args, &block)
    end

    def update_site_placements(*args, &block)
      return execute_action('update_site_placements', args, &block)
    end

    def get_placement_details_for_urls(*args, &block)
      return execute_action('get_placement_details_for_urls', args, &block)
    end

    def get_editorial_reasons_by_ids(*args, &block)
      return execute_action('get_editorial_reasons_by_ids', args, &block)
    end

    def get_account_migration_statuses(*args, &block)
      return execute_action('get_account_migration_statuses', args, &block)
    end

    def add_ad_extensions(*args, &block)
      return execute_action('add_ad_extensions', args, &block)
    end

    def get_ad_extensions_by_ids(*args, &block)
      return execute_action('get_ad_extensions_by_ids', args, &block)
    end

    def update_ad_extensions(*args, &block)
      return execute_action('update_ad_extensions', args, &block)
    end

    def delete_ad_extensions(*args, &block)
      return execute_action('delete_ad_extensions', args, &block)
    end

    def get_ad_extensions_editorial_reasons(*args, &block)
      return execute_action('get_ad_extensions_editorial_reasons', args, &block)
    end

    def set_ad_extensions_associations(*args, &block)
      return execute_action('set_ad_extensions_associations', args, &block)
    end

    def get_ad_extensions_associations(*args, &block)
      return execute_action('get_ad_extensions_associations', args, &block)
    end

    def delete_ad_extensions_associations(*args, &block)
      return execute_action('delete_ad_extensions_associations', args, &block)
    end

    def get_ad_extension_ids_by_account_id(*args, &block)
      return execute_action('get_ad_extension_ids_by_account_id', args, &block)
    end

    def add_media(*args, &block)
      return execute_action('add_media', args, &block)
    end

    def delete_media(*args, &block)
      return execute_action('delete_media', args, &block)
    end

    def get_media_by_ids(*args, &block)
      return execute_action('get_media_by_ids', args, &block)
    end

    def get_media_meta_data_by_account_id(*args, &block)
      return execute_action('get_media_meta_data_by_account_id', args, &block)
    end

    def get_media_meta_data_by_ids(*args, &block)
      return execute_action('get_media_meta_data_by_ids', args, &block)
    end

    def get_media_associations(*args, &block)
      return execute_action('get_media_associations', args, &block)
    end

    def get_ad_group_criterions_by_ids(*args, &block)
      return execute_action('get_ad_group_criterions_by_ids', args, &block)
    end

    def add_ad_group_criterions(*args, &block)
      return execute_action('add_ad_group_criterions', args, &block)
    end

    def update_ad_group_criterions(*args, &block)
      return execute_action('update_ad_group_criterions', args, &block)
    end

    def delete_ad_group_criterions(*args, &block)
      return execute_action('delete_ad_group_criterions', args, &block)
    end

    def apply_product_partition_actions(*args, &block)
      return execute_action('apply_product_partition_actions', args, &block)
    end

    def get_bmc_stores_by_customer_id(*args, &block)
      return execute_action('get_bmc_stores_by_customer_id', args, &block)
    end

    def add_negative_keywords_to_entities(*args, &block)
      return execute_action('add_negative_keywords_to_entities', args, &block)
    end

    def get_negative_keywords_by_entity_ids(*args, &block)
      return execute_action('get_negative_keywords_by_entity_ids', args, &block)
    end

    def delete_negative_keywords_from_entities(*args, &block)
      return execute_action('delete_negative_keywords_from_entities', args, &block)
    end

    def get_shared_entities_by_account_id(*args, &block)
      return execute_action('get_shared_entities_by_account_id', args, &block)
    end

    def add_shared_entity(*args, &block)
      return execute_action('add_shared_entity', args, &block)
    end

    def get_list_items_by_shared_list(*args, &block)
      return execute_action('get_list_items_by_shared_list', args, &block)
    end

    def add_list_items_to_shared_list(*args, &block)
      return execute_action('add_list_items_to_shared_list', args, &block)
    end

    def update_shared_entities(*args, &block)
      return execute_action('update_shared_entities', args, &block)
    end

    def delete_list_items_from_shared_list(*args, &block)
      return execute_action('delete_list_items_from_shared_list', args, &block)
    end

    def set_shared_entity_associations(*args, &block)
      return execute_action('set_shared_entity_associations', args, &block)
    end

    def delete_shared_entity_associations(*args, &block)
      return execute_action('delete_shared_entity_associations', args, &block)
    end

    def get_shared_entity_associations_by_shared_entity_ids(*args, &block)
      return execute_action('get_shared_entity_associations_by_shared_entity_ids', args, &block)
    end

    def get_shared_entity_associations_by_entity_ids(*args, &block)
      return execute_action('get_shared_entity_associations_by_entity_ids', args, &block)
    end

    def delete_shared_entities(*args, &block)
      return execute_action('delete_shared_entities', args, &block)
    end

    def get_campaign_sizes_by_account_id(*args, &block)
      return execute_action('get_campaign_sizes_by_account_id', args, &block)
    end

    def add_campaign_criterions(*args, &block)
      return execute_action('add_campaign_criterions', args, &block)
    end

    def update_campaign_criterions(*args, &block)
      return execute_action('update_campaign_criterions', args, &block)
    end

    def delete_campaign_criterions(*args, &block)
      return execute_action('delete_campaign_criterions', args, &block)
    end

    def get_campaign_criterions_by_ids(*args, &block)
      return execute_action('get_campaign_criterions_by_ids', args, &block)
    end

    def get_remarketing_lists(*args, &block)
      return execute_action('get_remarketing_lists', args, &block)
    end

    def add_ad_group_remarketing_list_associations(*args, &block)
      return execute_action('add_ad_group_remarketing_list_associations', args, &block)
    end

    def update_ad_group_remarketing_list_associations(*args, &block)
      return execute_action('update_ad_group_remarketing_list_associations', args, &block)
    end

    def get_ad_group_remarketing_list_associations(*args, &block)
      return execute_action('get_ad_group_remarketing_list_associations', args, &block)
    end

    def delete_ad_group_remarketing_list_associations(*args, &block)
      return execute_action('delete_ad_group_remarketing_list_associations', args, &block)
    end

    private

    def get_service_registry()
      return CampaignManagementServiceRegistry
    end

    def get_module()
      return BingAdsApi::V10::CampaignManagementService
    end
  end
end; end; end
