# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2015, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.9 on 2016-07-04 17:56:00.

require 'ads_common/savon_service'
require 'bing_ads_api/v9/ad_intelligence_service_registry'

module BingAdsApi; module V9; module AdIntelligenceService
  class AdIntelligenceService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://bingads.microsoft.com/AdIntelligence/v9'
      super(config, endpoint, namespace, :v9)
    end

    def get_publisher_keyword_performance(*args, &block)
      return execute_action('get_publisher_keyword_performance', args, &block)
    end

    def suggest_keywords_for_url(*args, &block)
      return execute_action('suggest_keywords_for_url', args, &block)
    end

    def get_estimated_bid_by_keyword_ids(*args, &block)
      return execute_action('get_estimated_bid_by_keyword_ids', args, &block)
    end

    def get_estimated_position_by_keyword_ids(*args, &block)
      return execute_action('get_estimated_position_by_keyword_ids', args, &block)
    end

    def get_estimated_bid_by_keywords(*args, &block)
      return execute_action('get_estimated_bid_by_keywords', args, &block)
    end

    def get_estimated_position_by_keywords(*args, &block)
      return execute_action('get_estimated_position_by_keywords', args, &block)
    end

    def get_historical_search_count(*args, &block)
      return execute_action('get_historical_search_count', args, &block)
    end

    def get_historical_keyword_performance(*args, &block)
      return execute_action('get_historical_keyword_performance', args, &block)
    end

    def suggest_keywords_from_existing_keywords(*args, &block)
      return execute_action('suggest_keywords_from_existing_keywords', args, &block)
    end

    def get_keyword_locations(*args, &block)
      return execute_action('get_keyword_locations', args, &block)
    end

    def get_keyword_categories(*args, &block)
      return execute_action('get_keyword_categories', args, &block)
    end

    def get_keyword_demographics(*args, &block)
      return execute_action('get_keyword_demographics', args, &block)
    end

    def get_bid_landscape_by_keyword_ids(*args, &block)
      return execute_action('get_bid_landscape_by_keyword_ids', args, &block)
    end

    def get_bid_landscape_by_ad_group_ids(*args, &block)
      return execute_action('get_bid_landscape_by_ad_group_ids', args, &block)
    end

    def get_account_auction_insight(*args, &block)
      return execute_action('get_account_auction_insight', args, &block)
    end

    def get_campaign_auction_insight(*args, &block)
      return execute_action('get_campaign_auction_insight', args, &block)
    end

    def get_ad_group_auction_insight(*args, &block)
      return execute_action('get_ad_group_auction_insight', args, &block)
    end

    def get_keyword_auction_insight(*args, &block)
      return execute_action('get_keyword_auction_insight', args, &block)
    end

    def get_auction_insight_data(*args, &block)
      return execute_action('get_auction_insight_data', args, &block)
    end

    def get_auction_insight_avail(*args, &block)
      return execute_action('get_auction_insight_avail', args, &block)
    end

    def get_auction_insight_available_children(*args, &block)
      return execute_action('get_auction_insight_available_children', args, &block)
    end

    def get_keyword_id_bid_estimation(*args, &block)
      return execute_action('get_keyword_id_bid_estimation', args, &block)
    end

    private

    def get_service_registry()
      return AdIntelligenceServiceRegistry
    end

    def get_module()
      return BingAdsApi::V9::AdIntelligenceService
    end
  end
end; end; end
