# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2015, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.9 on 2016-07-04 17:56:34.

require 'ads_common/savon_service'
require 'bing_ads_api/v9/customer_billing_service_registry'

module BingAdsApi; module V9; module CustomerBillingService
  class CustomerBillingService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://bingads.microsoft.com/Billing/v9'
      super(config, endpoint, namespace, :v9)
    end

    def get_billing_documents_info(*args, &block)
      return execute_action('get_billing_documents_info', args, &block)
    end

    def get_billing_documents(*args, &block)
      return execute_action('get_billing_documents', args, &block)
    end

    def get_display_invoices(*args, &block)
      return execute_action('get_display_invoices', args, &block)
    end

    def add_insertion_order(*args, &block)
      return execute_action('add_insertion_order', args, &block)
    end

    def update_insertion_order(*args, &block)
      return execute_action('update_insertion_order', args, &block)
    end

    def get_insertion_orders_by_account(*args, &block)
      return execute_action('get_insertion_orders_by_account', args, &block)
    end

    def search_insertion_orders(*args, &block)
      return execute_action('search_insertion_orders', args, &block)
    end

    def get_kohio_invoices(*args, &block)
      return execute_action('get_kohio_invoices', args, &block)
    end

    def get_account_monthly_spend(*args, &block)
      return execute_action('get_account_monthly_spend', args, &block)
    end

    private

    def get_service_registry()
      return CustomerBillingServiceRegistry
    end

    def get_module()
      return BingAdsApi::V9::CustomerBillingService
    end
  end
end; end; end
