# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2015, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.9 on 2016-07-04 17:56:39.

require 'ads_common/savon_service'
require 'bing_ads_api/v9/optimizer_service_registry'

module BingAdsApi; module V9; module OptimizerService
  class OptimizerService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://bingads.microsoft.com/Optimizer/v9'
      super(config, endpoint, namespace, :v9)
    end

    def get_budget_opportunities(*args, &block)
      return execute_action('get_budget_opportunities', args, &block)
    end

    def get_budget_landscape(*args, &block)
      return execute_action('get_budget_landscape', args, &block)
    end

    def get_bid_opportunities(*args, &block)
      return execute_action('get_bid_opportunities', args, &block)
    end

    def get_keyword_opportunities(*args, &block)
      return execute_action('get_keyword_opportunities', args, &block)
    end

    def get_broad_match_opportunities(*args, &block)
      return execute_action('get_broad_match_opportunities', args, &block)
    end

    def get_broad_match_search_queries(*args, &block)
      return execute_action('get_broad_match_search_queries', args, &block)
    end

    def apply_opportunity_modifiers(*args, &block)
      return execute_action('apply_opportunity_modifiers', args, &block)
    end

    def apply_opportunities(*args, &block)
      return execute_action('apply_opportunities', args, &block)
    end

    private

    def get_service_registry()
      return OptimizerServiceRegistry
    end

    def get_module()
      return BingAdsApi::V9::OptimizerService
    end
  end
end; end; end
