# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2015, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.9 on 2016-07-04 17:56:41.

require 'bing_ads_api/errors'

module BingAdsApi; module V9; module ReportingService
  class ReportingServiceRegistry
    REPORTINGSERVICE_METHODS = {:submit_generate_report=>{:input=>[], :output=>{:name=>"submit_generate_report_response", :fields=>[]}, :original_name=>"SubmitGenerateReport"}, :poll_generate_report=>{:input=>[], :output=>{:name=>"poll_generate_report_response", :fields=>[]}, :original_name=>"PollGenerateReport"}}
    REPORTINGSERVICE_TYPES = {}
    REPORTINGSERVICE_NAMESPACES = []

    def self.get_method_signature(method_name)
      return REPORTINGSERVICE_METHODS[method_name.to_sym]
    end

    def self.get_type_signature(type_name)
      return REPORTINGSERVICE_TYPES[type_name.to_sym]
    end

    def self.get_namespace(index)
      return REPORTINGSERVICE_NAMESPACES[index]
    end
  end
end; end; end
